FROM node:14-alpine as build
WORKDIR /app
COPY ./video-manager .
RUN rm -rf node_modules
RUN npm i
RUN npm run build

FROM nginx:1.19.9-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./.docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]