version: '3'

services:

    app:
        build: 
            context: .
            dockerfile: ./Dockerfile.dev
        container_name: frontend-video-manager-app
        volumes:
            - ./video-manager:/app
        tty: true
        restart: always
        ports:
            - "3000:3000"
        expose: 
            - "3000"
        