version: '3'

services:

    development-react:
        build: 
            context: .
            dockerfile: ./Dockerfile.dev
        container_name: video-manager-development-react
        volumes:
            - ./video-manager:/app
        tty: true
        restart: always
        ports:
            - "3000:3000"
        expose: 
            - "3000"
        