FROM nginx:1.15.0-alpine

ARG PORT
RUN echo $PORT
RUN rm /etc/nginx/conf.d/default.conf
COPY ./.docker/nginx/nginx.prod.conf /etc/nginx/conf.d
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/nginx.prod.conf && nginx -g 'daemon off;'

