version: '3'

services:

    development-app:
        build: 
            context: .
            dockerfile: ./Dockerfile.dev
        container_name: video-manager-development-app
        entrypoint: dockerize -template ./.docker/app/.env.dev:.env -wait tcp://development-mysql:3306 -timeout 40s ./.docker/entrypoint.sh
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        networks:
            - development-network
        depends_on:
            - development-mysql
            - development-redis

    development-nginx:
        build: 
            context: .
            dockerfile: ./.docker/nginx/Dockerfile.dev
        container_name: video-manager-development-nginx
        restart: always
        tty: true
        volumes:
            - .:/var/www
        ports:
            - "8000:80"
        environment:
            - PORT=80
        networks:
            - development-network
        depends_on:
            - development-app

    development-mysql:
        build: 
            context: .
            dockerfile: ./.docker/mysql/Dockerfile
        container_name: video-manager-development-mysql
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=development-video-manager
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - development-network

    development-redis:
        build: 
            context: .
            dockerfile: ./.docker/redis/Dockerfile
        container_name: video-manager-development-redis
        expose:
            - "6379"
        ports:
            - "6379:6379"
        networks:
            - development-network

networks:
    development-network:
        driver: bridge
