version: '3'

services:

    app:
        build: 
            context: .
            dockerfile: ./Dockerfile.prod
        container_name: backend-video-manager-app
        entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s ./.docker/entrypoint.sh
        ports:
            - "9000:9000"
        networks:
            - app-network
        depends_on:
            - mysql
            - redis

    nginx:
        build: 
            context: .
            dockerfile: ./.docker/nginx/Dockerfile
        container_name: backend-video-manager-nginx
        restart: always
        tty: true
        volumes:
            - .:/var/www
        ports:
            - "8000:80"
        environment:
            - PORT=80
        networks:
            - app-network
        depends_on:
            - app

    mysql:
        build: 
            context: .
            dockerfile: ./.docker/mysql/Dockerfile
        container_name: backend-video-manager-mysql
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=video_manager
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

    redis:
        build: 
            context: .
            dockerfile: ./.docker/redis/Dockerfile
        container_name: backend-video-manager-redis
        expose:
            - "6379"
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
