version: '3'

services:

    production-app:
        build: 
            context: .
            dockerfile: ./Dockerfile.prod
        container_name: video-manager-production-app
        entrypoint: dockerize -template ./.docker/app/.env.prod:.env -wait tcp://production-mysql:3306 -timeout 40s ./.docker/entrypoint.sh
        ports:
            - "9000:9000"
        networks:
            - app-network
        depends_on:
            - production-mysql
            - production-redis

    production-nginx:
        build: 
            context: .
            dockerfile: ./.docker/nginx/Dockerfile.prod
        container_name: video-manager-production-nginx
        restart: always
        tty: true
        volumes:
            - .:/var/www
        ports:
            - "8000:80"
        environment:
            - PORT=80
        networks:
            - production-network
        depends_on:
            - production-app

    production-mysql:
        build: 
            context: .
            dockerfile: ./.docker/mysql/Dockerfile
        container_name: video-manager-production-mysql
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=production-video-manager
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - production-network

    production-redis:
        build: 
            context: .
            dockerfile: ./.docker/redis/Dockerfile
        container_name: video-manager-production-redis
        expose:
            - "6379"
        ports:
            - "6379:6379"
        networks:
            - production-network

networks:
    production-network:
        driver: bridge
