name: ci-backend-video-manager
on: 
  push:
    branches:
      - feature/ci 
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Docker-compose down
        run: cd backend && docker-compose -f docker-compose.prod.yml down

      - name: Docker-compose build --no-cache
        run: cd backend && docker-compose -f docker-compose.prod.yml build --no-cache

      - name: Docker-compose down
        run: cd frontend && docker-compose -f docker-compose.prod.yml down

      - name: Docker rmi frontend_production-react
        run: docker rmi frontend_production-react:latest

      - name: Docker-compose build --no-cache
        run: cd frontend && docker-compose -f docker-compose.prod.yml build --no-cache
      
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} docker.io

      - name: Docker tag backend_production-app
        run: docker tag backend_production-app ${{ secrets.DOCKERHUB_USERNAME }}/video-manager-production-app:latest
  
      - name: Docker tag backend_production-nginx
        run: docker tag backend_production-nginx ${{ secrets.DOCKERHUB_USERNAME }}/video-manager-production-nginx:latest

      - name: Docker tag backend_production-mysql
        run: docker tag backend_production-mysql ${{ secrets.DOCKERHUB_USERNAME }}/video-manager-production-mysql:latest

      - name: Docker tag backend_production-redis
        run: docker tag backend_production-redis ${{ secrets.DOCKERHUB_USERNAME }}/video-manager-production-redis:latest
   
      - name: Docker tag frontend_production-react
        run: docker tag frontend_production-react ${{ secrets.DOCKERHUB_USERNAME }}/video-manager-production-react:latest
   
      - name: Docker push video-manager-production-app:latest
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/video-manager-production-app:latest
  
      - name: Docker push video-manager-production-nginx:latest
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/video-manager-production-nginx:latest

      - name: Docker push video-manager-production-mysql:latest
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/video-manager-production-mysql:latest

      - name: Docker push video-manager-redis:latest
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/video-manager-production-redis:latest
   
      - name: Docker push video-manager-react:latest
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/video-manager-production-react:latest
   



     